sudo: required
services:
  - docker

before_install:
  - docker build -t tpettigrew/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tpettigrew/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerRact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-506097553946'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
